hw1-1.o:
	gcc -Wall -o hw1-1.o hw1-1.c

hw1-2.S:
	gcc -O0 -S -o hw1-2.S hw1-2.c

hw1-2.O2.S:
	gcc -O2 -S -o hw1-2.O2.S hw1-2.c

hw1-3.o:
	gcc -Wall -o hw1-3.o hw1-3.c

hw1-4.o:
	gcc -Wall -o hw1-4.o hw1-4.c

hw1-1: hw1-1.o
	

hw1-2: hw1-2.S hw1-2.O2.S
	

hw1-3: hw1-3.o
	

hw1-4: hw1-4.o
	

